##服务配置
server:
  port: 9292
  tomcat:
    max-threads: 800
    uri-encoding: utf-8

##日志配置
logging:
  config: classpath:config/spring/springBoot-logbak-local.xml

##spring生态配置
spring:
  ##引入
  profiles:
    include: local-security
  ##应用名
  application:
      name: buukle-cms
  ##http编码
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  #datasource
  datasource:
    url: jdbc:mysql://localhost:3654/buukle-cms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: A987654321b/
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  ##redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 4376
    pool:
      #最大空闲连接
      max-idle: 100
      #最小空闲连接
      min-idle: 1
      #最大连接数(负数表示没有限制)
      max-active: 1000
      #最大阻塞等待时间(负数表示没有限制)
      max-wait: 20
    timeout: 3000

#clould注册中心 eureka 配置
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    serverport: 9090
  client:
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${eureka.instance.serverport}/eureka/
##mybatis
mybatis:
  mapper-locations: classpath*:/config/mapper/*.xml
  type-aliases-package: top.buukle.consumer.cms.entity
##===============================================================================================================================


